# Data cleanning dos dados referentes a casos de ataques de tubarão.

Primeira pergunta - Spray anti tubarão aonde vender?

In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
shark =  pd.read_csv('data/attacks.csv', sep = ',', encoding = 'windows-1252' )
shark.head(10)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris …,M,...,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0,NaN,NaN
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,...,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0,NaN,NaN
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,...,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0,NaN,NaN
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,...,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0,NaN,NaN
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,...,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294.0,NaN,NaN

In [16]:
shark.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex', 'age', 'injury', 'fatal_(y_n)', 'time',
       'species', 'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number.1', 'case_number.2', 'original_order'],
      dtype='object')

## Primeiras observações de arquivos:Nome das colunas, limpar valores nones , checar duplicadas.
colunas Unnamed? nan information? pdf??

### Arrumando as colunas e removendo as colunas vazias

In [15]:
shark.columns
shark.columns = [col.lower().replace(' ','_').replace('/','_') for col in shark.columns]
shark.rename(columns={'sex_':'sex','species_':'species'}, inplace = True)
shark.drop(['unnamed:_22','unnamed:_23'], axis = 1,inplace = True)

In [5]:
shark.head()

,case_number,date,year,type,country,area,location,activity,name,sex_,...,fatal_(y_n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0

### Removendo as duplicadas e valores nulos

In [6]:
shark = shark[~shark['case_number'].isna()]
shark = shark[shark['case_number'] != '0']
shark.head(10)

,case_number,date,year,type,country,area,location,activity,name,sex_,...,fatal_(y_n),time,species_,investigator_or_source,pdf,href_formula,href,case_number.1,case_number.2,original_order
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,N,14h00 -15h00,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,N,07h45,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0
5,2018.06.03.b,03-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Flat Rock, Ballina",Kite surfing,Chris …,M,...,N,NaN,NaN,"Daily Telegraph, 6/4/2018",2018.06.03.b-FlatRock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.b,2018.06.03.b,6298.0
6,2018.06.03.a,03-Jun-2018,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,...,Y,Late afternoon,Tiger shark,"Diario de Pernambuco, 6/4/2018",2018.06.03.a-daSilva.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.03.a,2018.06.03.a,6297.0
7,2018.05.27,27-May-2018,2018.0,Unprovoked,USA,Florida,"Lighhouse Point Park, Ponce Inlet, Volusia County",Fishing,male,M,...,N,NaN,"Lemon shark, 3'","K. McMurray, TrackingSharks.com",2018.05.27-Ponce.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.27,2018.05.27,6296.0
8,2018.05.26.b,26-May-2018,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,...,N,17h00,"Bull shark, 6'","K.McMurray, TrackingSharks.com",2018.05.26.b-High.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.b,2018.05.26.b,6295.0
9,2018.05.26.a,26-May-2018,2018.0,Unprovoked,USA,Florida,"Daytona Beach, Volusia County",Standing,male,M,...,N,14h00,NaN,"K. McMurray, Tracking Sharks.com",2018.05.26.a-DaytonaBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.05.26.a,2018.05.26.a,6294.0

# Escolhendo as categorias para analise
colunas: case_number;country;area

In [7]:
shark.columns

Index(['case_number', 'date', 'year', 'type', 'country', 'area', 'location',
       'activity', 'name', 'sex_', 'age', 'injury', 'fatal_(y_n)', 'time',
       'species_', 'investigator_or_source', 'pdf', 'href_formula', 'href',
       'case_number.1', 'case_number.2', 'original_order'],
      dtype='object')

In [29]:
shark_country = shark.loc[:,['case_number','year','country', 'area','location','name','sex','age']]
shark_country = shark_country[~shark_country['country'].isna()]
print(shark_country['country'].unique())
print(shark_country['country'].value_counts())

['USA' 'AUSTRALIA' 'MEXICO' 'BRAZIL' 'ENGLAND' 'SOUTH AFRICA' 'THAILAND'
 'COSTA RICA' 'MALDIVES' 'BAHAMAS' 'NEW CALEDONIA' 'ECUADOR' 'MALAYSIA'
 'LIBYA' 'CUBA' 'MAURITIUS' 'NEW ZEALAND' 'SPAIN' 'SAMOA'
 'SOLOMON ISLANDS' 'JAPAN' 'EGYPT' 'ST HELENA, British overseas territory'
 'COMOROS' 'REUNION' 'FRENCH POLYNESIA' 'UNITED KINGDOM'
 'UNITED ARAB EMIRATES' 'PHILIPPINES' 'INDONESIA' 'CHINA' 'COLUMBIA'
 'CAPE VERDE' 'Fiji' 'DOMINICAN REPUBLIC' 'CAYMAN ISLANDS' 'ARUBA'
 'MOZAMBIQUE' 'FIJI' 'PUERTO RICO' 'ITALY' 'ATLANTIC OCEAN' 'GREECE'
 'ST. MARTIN' 'FRANCE' 'PAPUA NEW GUINEA' 'TRINIDAD & TOBAGO' 'KIRIBATI'
 'ISRAEL' 'DIEGO GARCIA' 'TAIWAN' 'JAMAICA' 'PALESTINIAN TERRITORIES'
 'GUAM' 'SEYCHELLES' 'BELIZE' 'NIGERIA' 'TONGA' 'SCOTLAND' 'CANADA'
 'CROATIA' 'SAUDI ARABIA' 'CHILE' 'ANTIGUA' 'KENYA' 'RUSSIA'
 'TURKS & CAICOS' 'UNITED ARAB EMIRATES (UAE)' 'AZORES' 'SOUTH KOREA'
 'MALTA' 'VIETNAM' 'MADAGASCAR' 'PANAMA' 'SOMALIA' 'NEVIS'
 'BRITISH VIRGIN ISLANDS' 'NORWAY' 'SENEGAL' 'YEMEN' 'GULF OF ADEN'
 'Sierra Leone' 'ST. MAARTIN' 'GRAND CAYMAN' 'Seychelles' 'LIBERIA'
 'VANUATU' 'MEXICO ' 'HONDURAS' 'VENEZUELA' 'SRI LANKA' ' TONGA' 'URUGUAY'
 'INDIA' 'MICRONESIA' 'CARIBBEAN SEA' 'OKINAWA' 'TANZANIA'
 'MARSHALL ISLANDS' 'EGYPT / ISRAEL' 'NORTHERN ARABIAN SEA' 'HONG KONG'
 'EL SALVADOR' 'ANGOLA' 'BERMUDA' 'MONTENEGRO' 'IRAN' 'TUNISIA' 'NAMIBIA'
 'NORTH ATLANTIC OCEAN' 'PORTUGAL' 'SOUTH CHINA SEA' 'BANGLADESH' 'PALAU'
 'WESTERN SAMOA' 'PACIFIC OCEAN ' 'BRITISH ISLES' 'GRENADA' 'IRAQ'
 'TURKEY' 'SINGAPORE' 'NEW BRITAIN' 'SUDAN' 'JOHNSTON ISLAND'
 'SOUTH PACIFIC OCEAN' 'NEW GUINEA' 'RED SEA' 'NORTH PACIFIC OCEAN'
 'FEDERATED STATES OF MICRONESIA' 'MID ATLANTIC OCEAN' 'ADMIRALTY ISLANDS'
 'BRITISH WEST INDIES' 'SOUTH ATLANTIC OCEAN' 'PERSIAN GULF'
 'RED SEA / INDIAN OCEAN' 'PACIFIC OCEAN' 'NORTH SEA' 'NICARAGUA '
 'MALDIVE ISLANDS' 'AMERICAN SAMOA' 'ANDAMAN / NICOBAR ISLANDAS' 'GABON'
 'MAYOTTE' 'NORTH ATLANTIC OCEAN ' 'THE BALKANS' 'SUDAN?' 'ARGENTINA'
 'MARTINIQUE' 'INDIAN OCEAN' 'GUATEMALA' 'NETHERLANDS ANTILLES'
 'NORTHERN MARIANA ISLANDS' 'IRAN / IRAQ' 'JAVA' 'SIERRA LEONE'
 ' PHILIPPINES' 'NICARAGUA' 'CENTRAL PACIFIC' 'SOLOMON ISLANDS / VANUATU'
 'SOUTHWEST PACIFIC OCEAN' 'BAY OF BENGAL' 'MID-PACIFC OCEAN' 'SLOVENIA'
 'CURACAO' 'ICELAND' 'ITALY / CROATIA' 'BARBADOS' 'MONACO' 'GUYANA'
 'HAITI' 'SAN DOMINGO' 'IRELAND' 'KUWAIT' 'YEMEN ' 'REUNION ISLAND'
 'FALKLAND ISLANDS' 'CRETE' 'CYPRUS' 'EGYPT ' 'WEST INDIES' 'BURMA'
 'LEBANON' 'PARAGUAY' 'BRITISH NEW GUINEA' 'CEYLON' 'OCEAN' 'GEORGIA'
 'SYRIA' 'TUVALU' 'INDIAN OCEAN?' 'GUINEA' 'ANDAMAN ISLANDS'
 'EQUATORIAL GUINEA / CAMEROON' 'COOK ISLANDS' 'TOBAGO' 'PERU' 'AFRICA'
 'ALGERIA' 'Coast of AFRICA' 'TASMAN SEA' 'GHANA' 'GREENLAND'
 'MEDITERRANEAN SEA' 'SWEDEN' 'ROATAN' 'Between PORTUGAL & INDIA'
 'DJIBOUTI' 'BAHREIN' 'KOREA' 'RED SEA?' 'ASIA?' 'CEYLON (SRI LANKA)']
USA                       2228
AUSTRALIA                 1338
SOUTH AFRICA               579
PAPUA NEW GUINEA           134
NEW ZEALAND                128
                          ...
MALDIVE ISLANDS              1
NICARAGUA                    1
NORTH SEA                    1
RED SEA / INDIAN OCEAN       1
CEYLON (SRI LANKA)           1
Name: country, Length: 212, dtype: int64

## USA e Australia são as melhores areas para iniciar a venda do spray de tubarão?
### Aonde desses paises ??

In [30]:
print(shark_country.count())

case_number    6251
year           6249
country        6251
area           5831
location       5750
name           6045
sex            5690
age            3462
dtype: int64

USA representa 35% dos ataques de tubarões
Australia 21% dos ataques de tubaroes

In [31]:
shark_area = shark_country[(shark_country['country'] == 'USA')|(shark_country['country'] == 'AUSTRALIA')]
print(shark_area['area'].value_counts().head(7))
print(shark_area.count())

Florida              1036
New South Wales       486
Queensland            311
Hawaii                298
California            290
Western Australia     189
South Carolina        159
Name: area, dtype: int64
case_number    3566
year           3565
country        3566
area           3548
location       3471
name           3517
sex            3327
age            2226
dtype: int64

USA - Florida(29%), Hawaii(8%) e California(8%)

Australia -  New south wales(13%), Queensland(8%) e Western Australia(5%)

## Recencia desses dados
### Trabalhando com 'year'
        Conferindo os dados num corte menor

In [32]:
shark_2010 = shark_country[shark_country['year'] > 2010]
print(shark_2010['case_number'].count())
shark_2010['country'].value_counts()

954

USA                           450
AUSTRALIA                     204
SOUTH AFRICA                   56
BAHAMAS                        31
REUNION                        22
                             ...
COMOROS                         1
PUERTO RICO                     1
ARUBA                           1
CHINA                           1
UNITED ARAB EMIRATES (UAE)      1
Name: country, Length: 68, dtype: int64

#### Conclusoes country
954 casos recentes desde os anos 2010

USA(47%) e Australia(21%) continuam como os mais relevantes nos casos mais recentes.

Os USA Aumentaram significamente o numero de ataques nos anos recentes, se tornando um mercado ainda melhor para a implementação do produto.

In [33]:
print(shark_2010['area'].value_counts().head(7))
shark_2010.count()

Florida              212
New South Wales       78
Hawaii                70
Western Australia     59
California            57
South Carolina        44
Queensland            31
Name: area, dtype: int64

case_number    954
year           954
country        954
area           907
location       909
name           941
sex            919
age            715
dtype: int64

#### conclusoes area
954 casos recentes desde os anos 2000, temos a area desconhecida para 50 mas todos são fora da nossa area de interesse

Florida(27%), ja como havia indicado, se torna o melhor local para o Inicio da venda do produto dentro dos USA e no mundo, seguido por Hawaii(8%) e California(5%)
New South Wales(8%)

# Entender o perfil do cliente
## Genero

In [105]:
shark_area['sex'].unique()
shark_area[~(shark_area['sex'] == 'F') & ~(shark_area['sex'] == 'M')]

,case_number,year,country,area,location,name,sex,age
86,2017.09.14,2017.0,AUSTRALIA,Westerm Australia,Esperance,NaN,I,NaN
154,2017.04.17.b,2017.0,USA,Florida,"Daytona Beach, Volusia County",NaN,I,NaN
179,2017.02.01.b,2017.0,USA,South Carolina,16 miles off Hilton Head,Chip Michelove & crew,I,NaN
218,2016.09.15.R,2016.0,AUSTRALIA,Western Australia,Bunbury,Occupant: Ben Stratton,I,NaN
243,2016.07.17,2016.0,USA,Alabama,8 miles off Mobile,Occupant: Ben Raines,I,NaN
...,...,...,...,...,...,...,...,...
6062,1842.07.06,1842.0,USA,New Jersey,"Absecon, Atlantic County",male,I,NaN
6070,1840.02.00,1840.0,AUSTRALIA,Tasmania,George Town Cove,A dinghy,I,NaN
6081,1836.00.00.a,1836.0,AUSTRALIA,South Australia,NaN,NaN,I,NaN
6127,1804.02.26.R,1804.0,AUSTRALIA,New South Wales,"Georges Head, off Port Jackson",boat,I,NaN
6136,1788.05.10,1788.0,AUSTRALIA,New South Wales,Sydney Harbor,boat,I,NaN

Temos 243 entradas sem dados tratados sobre genero vamos tentar achar essas informações dentro da propria tabela

In [103]:
shark_area.loc[shark_area['sex'] == 'M ','sex'] = shark_area.loc[shark_area['sex'] == 'M ','sex'].replace('M ','M')
shark_area.loc[shark_area['sex'] =='lli','sex'] = shark_area.loc[shark_area['sex'] == 'lli','sex'].replace('lli','M')
shark_area.loc[shark_area['sex'] == 'N','sex'] = shark_area.loc[shark_area['sex'] == 'N','sex'].replace('N','I')
shark_area.loc[shark_area['sex'].isna(),'sex'] = shark_area.loc[shark_area['sex'].isna(),'sex'].replace(np.nan,'I')

Algumas entradas puderam ser transformadas mas outras foram categorizadas como 'I' de indefinido podendo ser multiplas pessoas ou embarcações

In [110]:
print(shark_area['sex'].count)
shark_area['sex'].value_counts()

<bound method Series.count of 0       F
1       F
2       M
3       M
5       M
       ..
6295    M
6296    M
6297    M
6298    M
6299    M
Name: sex, Length: 3566, dtype: object>

M    2901
F     425
I     240
Name: sex, dtype: int64

A população masculina(81%) é de longe a mais afetada nas interações com tubarões

### Idade
Temos alguma idades que não estão precisas mas entre intervalos para isso aproximaremos para o valor mais baixo

Para valores nulos vamos investigar se a informações que podemo ser adiquiridas na tabela

In [279]:
shark_male['age'].unique()

array(['48', nan, '52', '15', '12', '32', '10', '60', '29', '41', '37',
       '25', '69', '18', '34', '35', '14', '28', '7', '31', '17', '54',
       '33', '13', '40', '50', '46', '19', '73', '16', '39', '58', '30',
       '26', '22', '55', '57', '47', '20', '61', '65', '42', '36', '21',
       '43', '9', '49', '59', '11', '27', '64', '71', '44', '62', '38',
       '68', '6', '63', '70', '53', '23', '8', '45', '3', '51', '24',
       '56', '5', '86', '66', '84', '75', '87', '67', '74', '78'],
      dtype=object)

In [277]:
shark_male.loc[:,'age'] = shark_male.loc[:,'age'].replace('[A-z]',np.nan, regex = True)

C:\Users\Botelho\AppData\Local\Temp\ipykernel_8508\1613267080.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_male.loc[:,'age'] = shark_male.loc[:,'age'].replace('.[A-z].',np.nan, regex = True)

In [278]:
shark_male = shark_area[shark_area['sex'] == 'M']
shark_male[(shark_male['age'].str.contains('[A-z]',regex = True, na = False)) & ~(shark_male['age'].isna())]
shark_male.loc[shark_male['age'] == 'Teen','age'] = shark_male.loc[shark_male['age'] == 'Teen','sex'].replace('Teen',13)
shark_male.loc[shark_male['age'] =='Teens','age'] = shark_male.loc[shark_male['age'] == 'Teens','sex'].replace('Teens',13)
shark_male.loc[shark_male['age'] == 'teen','age'] = shark_male.loc[shark_male['age'] == 'teen','sex'].replace('teen',13)
shark_male.loc[shark_male['age'] == 'Elderly','age'] = shark_male.loc[shark_male['age'] == 'Elderly','sex'].replace('Elderly',65)
shark_male.loc[shark_male['age'] == '"young"','age'] = shark_male.loc[shark_male['age'] == '"young"','sex'].replace('"young"',5)
shark_male.loc[shark_male['age'] == 'young','age'] = shark_male.loc[shark_male['age'] == 'young','sex'].replace('young',5)
shark_male.loc[shark_male['age'] == 'adult','age'] = shark_male.loc[shark_male['age'] == 'adult','sex'].replace('adult',30)
shark_male.loc[shark_male['age'] == 'Both 11','age'] = shark_male.loc[shark_male['age'] == 'Both 11','sex'].replace('Both 11',11)
shark_male.loc[shark_male['age'] == 'mid-20s','age'] = shark_male.loc[shark_male['age'] == 'mid-20s','sex'].replace('mid-20s',25)
shark_male.loc[shark_male['age'] == 'mid-30s','age'] = shark_male.loc[shark_male['age'] == 'mid-30s','sex'].replace('mid-30s',30)
shark_male.loc[:,'age'] = shark_male.loc[:,'age'].str.replace('.*?([0-9]{1,3}).*',r'\1', regex = True)
shark_male.loc[:,'age'] = shark_male.loc[:,'age'].replace('[A-z]',np.nan, regex = True)
shark_male.loc[:,'age'] = shark_male.loc[:,'age'].replace(' ',np.nan, regex = True)

C:\Users\Botelho\AppData\Local\Temp\ipykernel_8508\814773850.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_male.loc[:,'age'] = shark_male.loc[:,'age'].str.replace('.*?([0-9]{1,3}).*',r'\1', regex = True)
C:\Users\Botelho\AppData\Local\Temp\ipykernel_8508\814773850.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_male.loc[:,'age'] = shark_male.loc[:,'age'].replace('[A-z]',np.nan, regex = True)
C:\Users\Botelho\AppData\Local\Temp\ipykernel_8508\814773850.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_male.loc[:,'age'] = shark_male.loc[:,'age'].replace(' ',np.nan, regex = True)

Apos fazer a limpeza da tabela podemos transformala em inteiro para fazer a divisão por idade

In [302]:
shark_male['age'] = pd.to_numeric(shark_male['age'])

C:\Users\Botelho\AppData\Local\Temp\ipykernel_8508\1172513818.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_male['age'] = pd.to_numeric(shark_male['age'])

27.377440347071584

In [311]:
print(shark_male['age'].mean())
print(shark_male['age'].quantile())
print(shark_male['age'].quantile(q = 0.75))
print(shark_male['age'].quantile(q = 0.25))
print(shark_male[shark_male['age'] < 17].count())

27.377440347071584
24.0
35.0
17.0
case_number    409
year           409
country        409
area           409
location       407
name           408
sex            409
age            409
dtype: int64

Mesmo com uma grande falta de daos podemos ver que 75% casos acontecem ate 35 anos e 50% ate 24 anos . Assim temos essa faixa etaria mais nova como publico alvo

# 4 Conclusões
## Localidade 
Ficou clara pela analise de dados que tanto os USA e a Australia são paises propricios para o lançamento do spray, por serem os 2 que tem o maior encontro entre tubarões e pessoas(56%) dos casos totais.

As localidades mais propricias em cada um dos paises escolhidos foram:

USA - Florida(29%), Hawaii(8%) e California(8%)

Australia - New south wales(13%), Queensland(8%) e Western Australia(5%)

## Grupo alvo
Outro analise feita foi para quem esse produto deve ser divulgado e o nosso candidato ideal é:

Homem(80%) mais novo na faixa entra 17 - 35(50%) que representa 40% de todos os casos já registrados de ataques de tubarões